### PR TITLE
Add DangerBot

### PR DESCRIPTION
**Pull request by sxcore**

### CODE REVIEW

**Comment by Drwalcore** [comment]
I just noticed that I wasn't fully aware that we need to add **ELDangerBot** to repo members - that's the reason the tests failed 👎  If someone from @elpassion/ios-team with admin privileges could add it as member I would be happy to complete this PR :)

**Comment by darrarski** [comment]
@Drwalcore done ✅

**Comment by Drwalcore** [comment]
Okay, thank You, I will restart failed Build on Travis 🚀

**Comment by darrarski** [comment]
I added Danger API token to Travis CI and restarted last build. Let's hope it will work this time.

**Comment by Drwalcore** [comment]
@darrarski Thank You for helping, I see some progress here 👍 
I will fix that immediately.

**Comment by Drwalcore** [comment]
[[iOS] Add DangerBot and improve Fastlane](https://trello.com/c/gr1vszkK/105-ios-add-dangerbot-and-improve-fastlane)

**Review by mateuszszklarek — APPROVED** [review]
LGTM 👍

**Pull request merged**
